sudo: required
env:
  matrix:
    - TEST_TARGET=rspec-ruby25
    - TEST_TARGET=rspec-ruby24
    - TEST_TARGET=rspec-ruby23
services:
  - docker
before_install:
  - docker-compose build
  - docker-compose up -d
install:
before_script:
script:
  - docker-compose exec ${TEST_TARGET} rspec
after_script:
notifications:
