sudo: required
services:
  - docker
before_install:
  - docker-compose up -d
install:
before_script:
script:
  - docker-compose exec rspec-ruby25 rspec
  - docker-compose exec rspec-ruby24 rspec
  - docker-compose exec rspec-ruby23 rspec
after_script:
notifications:
